---
# tasks file for ansible-zabbix-docker
- name: Create zabbix network
  docker_network:
    name: zabbix_network
    driver_options:
      com.docker.network.enable_ipv6: "false"
    ipam_options:
      subnet: "{{ zabbix_subnet }}"
      gateway: "{{ zabbix_gateway }}"

- name: Set zabbix-db state to {{ container_state }}
  docker_container:
    name: zabbix-db
    image: mysql:5.7
    state: "{{ container_state }}"
    volumes: "{{ zabbix_db_volumes }}"
    env: "{{ zabbix_db_env }}"
    purge_networks: yes
    networks:
      - name: zabbix_network
        aliases:
          - mysql-server
          - zabbix-database
          - mysql-database
  tags: zabbix-db

- name: Set zabbix-server state to {{ container_state }}
  docker_container:
    name: zabbix-server
    image: zabbix/zabbix-server-mysql
    state: "{{ container_state }}"
    ulimits:
      - nofile:20000:40000
      - nproc:65535
    memory: 512MB
    ports:
      - "10051:10051"
    volumes: "{{ zabbix_shared_volumes | union(zabbix_server_volumes) }}"
    links:
      - zabbix-db:zabbix-db
    env: "{{ zabbix_db_env | combine(zabbix_srv_env) }}"
    purge_networks: yes
    networks:
      - name: zabbix_network
        aliases:
         - zabbix-server
         - zabbix-server-mysql
  tags: zabbix-server

- name: Set zabbix-web state to {{ container_state }}
  docker_container:
    name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql
    state: "{{ container_state }}"
    memory: 512MB
    ports:
      - "80:80"
      - "443:443"
    volumes: "{{ zabbix_web_volumes }}"
    links:
      - zabbix-db:zabbix-db
      - zabbix-server:zabbix-server
    env: "{{ zabbix_db_env | combine(zabbix_web_env) }}"
    purge_networks: yes
    networks:
      - name: zabbix_network
        aliases:
         - zabbix-web-nginx-mysql
  tags: zabbix-web

- name: Set zabbix-agent state to {{ container_state }}
  docker_container:
    name: zabbix-agent
    image: zabbix/zabbix-agent
    state: "{{ container_state }}"
    ports:
      - "10050:10050"
    volumes: "{{ zabbix_shared_volumes | union(zabbix_agent_volumes) }}"
    links:
      - zabbix-server:zabbix-server
    env: "{{ zabbix_agent_env }}"
    privileged: true
    pid_mode: "host"
    purge_networks: yes
    networks:
      - name: zabbix_network
        aliases:
         - zabbix-agent
         - zabbix-agent-passive
  tags: zabbix-agent

- name: Check if zabbix is up
  uri:
    url: "http://localhost"
  when: container_state == 'started'
  register: uri_result
  until: uri_result.status == 200
  retries: 10
  tags: wait
